apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular-ui
  name: angular-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-ui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angular-ui
    spec:
      containers:
      - image: k8workshopregistry.azurecr.io/angular-ui:latest
        name:  angular-ui
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: angular-ui
  name: angular-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: angular-ui
  type: LoadBalancer
