apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-frontend
  name: spring-boot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-frontend
    spec:
      containers:
      - image: k8workshopregistry.azurecr.io/hello-world-java:latest
        name:  spring-boot-frontend
        resources: {}
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-frontend
  name: spring-boot-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-frontend
  type: LoadBalancer
