apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  namespace: jenkins
spec:
  containers:
    - name: springboot
      image: k8workshopregistry.azurecr.io/hello-world-java:latest
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: acr-secret
